### ISSUE TITLE
Would love to see this done as an XSL 

### ISSUE THREAD

**Issue by cooperaj** [r0tational/killteam-battlescribe#1]
If you could get this working as an XSL that would be great. That way you could use it directly as a part of the Battlescribe export.

**Comment by r0tational** [comment]
[Daeron Algos might add](https://reddit.com/r/killteam/comments/ejgcny/_/fcyylr9/?context=1) this as an XSL in their stylesheets :) Watch https://github.com/DaeronAlagos/battlescribe-stylesheets
