### ISSUE TITLE
<span class="bold"> doesn't show when using 40k CSS

### ISSUE THREAD

**Issue by Maltavius** [r0tational/killteam-battlescribe#2]
All <span> with class="bold" doesn't show up when using the 40k CSS.

**Comment by r0tational** [comment]
This is intended to declutter the list by removing all mentions of “Categories:”, “Abilities:” and “Selections:”, so you just see your units’ selections and attributes. Are you finding it’s removing anything else?

If you want to stop this from happening, just remove the line `div.battlescribe span.bold { display: none; }`

**Comment by Maltavius** [comment]
Yes, it removes alot more than that, Suddenly I have descriptions of rules I don't have the name of, mainly because the rule hitting Force Rules and Section Rules.

It also removes  "Rules:", "Codex Discipline:", "Psychic Power:", "Psyker:", "Unit:", "Weapon:"
And every header under Force Rules
"Angels of Death:", "Bolter Discipline:","Shock Assault:"
As well as under Selection Rules
"Angels of Death:", "Codex Discipline:", "Explodes (6"/D6):"

**Comment by r0tational** [comment]
I see what you mean. OK, I’m going to reinstate the rule names by replacing `li.force > p.rule-names { display: none; }` with:

```
li.force > p.rule-names { 
  margin-bottom: 20px;
  margin-left: 0px;
  margin-top: -12px;
  font-variant: small-caps;
  font-weight: bold;
  font-size: 16px;
 }
```

And for greater clarity, I’ll reinstate those bold “Selections”, “Categories” etc.

As for the profile names, each ability, psychic power and weapon is listed below along with their attributes and rules, so having them also listed here seems like clutter to me. I’m going to keep suppressing them for now, but if I’ve missed a bit of info that this section is displaying and isn’t clearly showing elsewhere in a unit’s listing, let me know. 

In the meantime, you can remove the line `div.battlescribe p.profile-names { display: none; }` to make them appear again (but their spacing will be a bit screwy).

**Comment by Maltavius** [comment]
Yes, that was much better.

I agree about the profile-names thing, It redundant since they are mostly listed below.
